apiVersion: v1
kind: ServiceAccount
metadata:
  name: liferay
---
apiVersion: v1
kind: Service
metadata:
  name: liferay
  labels:
    run: liferay
spec:
  type: LoadBalancer
  selector:
    run: liferay
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  sessionAffinity: ClientIP
