version: '3.5'

services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: lportal@lfrgs-dj-pg
      PGADMIN_DEFAULT_PASSWORD: DevTest123
    ports:
      - "80:80"
    restart: unless-stopped
