apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-files
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-files
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
