apiVersion: v1
kind: PersistentVolume
metadata:
  name: liferay-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  azureFile:
    secretName: azure-secret
    shareName: liferay-files
    readOnly: false
  claimRef:
    namespace: default
    name: liferay-files
